### PR TITLE
Changed style of quotes

### PR DESCRIPTION
**Pull request by biancaferreiralp**

### CODE REVIEW

**Comment by saman** [comment]
Thanks, @biancaferreiralp,
The "-" character is intentional; may I ask why you removed it?
I would agree with removing the "loading".

Thanks for your PR.

**Comment by biancaferreiralp** [comment]
Hi, Saman!

Oh my god, I'm so sorry! I did the changes believing it would go just to my
repo (the one I forked). It was just a matter of style that I preferred!
Not that had something wrong to do with it hahah I ended up forking so I
could host in my GH Pages, because I also wanted to experiment.

Did something change in your code?

Again, I'm so sorry! It wasn't the intention. I really liked the widget you
developed and am already using it :)

Kind regards,

*Bianca Ferreira*

Em seg., 22 de fev. de 2021 às 13:26, Saman Soltani <
notifications@github.com> escreveu:

**Comment by saman** [comment]
Great, happy to see you liked it this much that you want to customize it for yourself.
No worries, nothing has changed as I didn't merge your pull request.

I'll close the PR.

Thanks.

**Comment by biancaferreiralp** [comment]
Ah, perfect!

Good to know. And yes, I really liked it! Was looking forward to something
just like it.

Thank you for developing it :)

Have a nice week!

*Bianca Ferreira*


Em seg., 22 de fev. de 2021 às 13:38, Saman Soltani <
notifications@github.com> escreveu:

**Comment by biancaferreiralp** [comment]
Hi, Saman!

I just sent a new pull request to my forked repository to make sure I
changed the configurations and they won't get to you anymore. From what I
saw, it was indicating there that once I opened a new PR it would go to
your repo, and I changed to go to my master.

[image: image.png]

[image: image.png]

If a new PR still shows up to you, let me know so I can check it out!

*Bianca Ferreira*

Em seg., 22 de fev. de 2021 às 13:44, Bianca Ferreira <
biancaferreiralp@gmail.com> escreveu:

**Pull request closed without merging**
